### ISSUE TITLE
Optimize the installation

### ISSUE THREAD

**Issue by dragonexpert** [lukasamd/MyBB-Users-Browsed-Topic#3]
You can make use of the $db->insert_query_multiple method in your installation to reduce the number of queries.  It takes one parameter, a multidimensional array with the data.

**Comment by Eldenroot** [comment]
+1

**Comment by lukasamd** [comment]
Optimize... installation...? One process for whole plugin usage?
Hm... I do not see much sense, but thanks for info about insert_query_multiple method.
