### ISSUE TITLE
Extra space before the comma

### ISSUE THREAD

**Issue by Eldenroot** [lukasamd/MyBB-Users-Browsed-Topic#4]
![bug](https://cloud.githubusercontent.com/assets/778890/13049969/b3fa6766-d3f0-11e5-850a-d1c6993b2fbd.png)

There is extra space before the comma after every username

**Comment by lukasamd** [comment]
Disable output templates comments in ACP -> Server and Optimization Options.
It isn't plugin-related issue, MyBB adds comments with whitespaces ;)

**Comment by Eldenroot** [comment]
It is disabled in ACP... is possible that HTML minify plugin from @svepu can do this?
